language: python
python:
  - 3.6
  - 3.8
env:
  - DJANGO_VERSION=2.2
  - DJANGO_VERSION=3.1
install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
script:
  - python setup.py test
