language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO=1.10
  - DJANGO=1.11
install:
	- pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
script:
	- python setup.py test
