language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.8
env:
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=2.0a1
  - DJANGO_VERSION=2.2
matrix:
  exclude:
    - python: 2.7
      env: DJANGO_VERSION=2.0a1
install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
script:
  - python setup.py test
